server:
  port: 9901
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.127.218:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  session:
    store-type: none
logging:
  level:
    org:
      hibernate:
        SQL: debug


# ddl-auto: create   // 每次启动都会创建新的表
#           validate
#           update //每次启动更新表结构